// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXsl1SnoI6Hb96Z6Uc6vp-s15q_B4ouk',
    appId: '1:1793777775:web:902321424be5c714356d9a',
    messagingSenderId: '1793777775',
    projectId: 'insulin-dose-calculation',
    authDomain: 'insulin-dose-calculation.firebaseapp.com',
    storageBucket: 'insulin-dose-calculation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHzBVIMDSX1CpXDPNIEAnrC0M2y1JpGg',
    appId: '1:1793777775:android:cbef966d42c95e2b356d9a',
    messagingSenderId: '1793777775',
    projectId: 'insulin-dose-calculation',
    storageBucket: 'insulin-dose-calculation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxaVvHOrxfcO4W44DjW954Fd1ehMFTHks',
    appId: '1:1793777775:ios:2923d8002411e6bd356d9a',
    messagingSenderId: '1793777775',
    projectId: 'insulin-dose-calculation',
    storageBucket: 'insulin-dose-calculation.appspot.com',
    iosBundleId: 'com.example.insulinDoseCalculation',
  );
}
